version: '3.8'

services:
  access-service:
    build:
      context: /home/whtvr/go/vigilant-chainsaw-puppy   # Путь к папке с Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: access_db
    ports:
      - "5432:5432"
